import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { Toaster } from "sonner";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const robotoFont = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  style: ["normal", "italic"],
  weight: ["400", "500", "700"],
  preload: true,
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={robotoFont.className}>
        <Toaster
          richColors
          theme="light"
          // toastOptions={{
          //   unstyled: true,
          //   classNames: { toast: "bg-red-500", title: "text-red-500" },
          // }}
          position="top-right"
        />
        <Header />
        {children}
      </body>
    </html>
  );
}
