"use client";
import CategoryGrid from "@/components/CategorySection";
import FashionBackground from "@/components/fashonHero";
import { useRef } from "react";

// export const metadata: Metadata = {
//   title: "PARA MI CON MUCHO AMOR",
//   description: "Generated by create next app",
// };

export default function HomeLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const sectionRef = useRef<HTMLDivElement | null>(null);

  return (
    <div className="min-h-screen bg-gray-100">
      <FashionBackground />
      <div
        ref={sectionRef}
        className="container mx-auto flex max-w-7xl flex-wrap px-2 py-8"
      >
        <CategoryGrid />
        <h2 className="mb-4 text-center text-2xl font-bold">PROMOCIONES</h2>
        {children}
      </div>
    </div>
  );
}
